# Generated by Django 6.1 on 2026-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='Collaboration Inquiry', max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('ai_validation_status', models.CharField(choices=[('GENUINE', 'Verified Genuine'), ('SUSPICIOUS', 'Suspicious / Review'), ('BLOCKED_DISPOSABLE', 'Blocked Disposable/Fake'), ('SPAM', 'Spam')], default='GENUINE', max_length=50)),
                ('ai_analysis_notes', models.TextField(blank=True, default='Verified by AI Gatekeeper.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
