# Generated by Django 6.1 on 2026-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Md Tareq Shah Alam', max_length=150)),
                ('headline', models.CharField(default='Machine Learning Engineer & Data Scientist', max_length=255)),
                ('bio', models.TextField(default='Passionate about extracting actionable insights from data and architecting cutting-edge AI solutions. Specializing in NLP, Transformers, CNNs, LangChain, LlamaIndex, and advanced SQL workflows to solve complex real-world challenges.')),
                ('email', models.EmailField(default='tareqshah.027@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+8801625801530', help_text='Phone number with country code for Talk with me button', max_length=50)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=150)),
                ('blog_url', models.URLField(default='https://medium.com/@tareqshahalam', help_text="Blog / Medium / Articles URL for 'Read Articles' buttons")),
                ('github_url', models.URLField(blank=True, default='https://github.com/tareqshah027')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/md-tareq-shah-alam/')),
                ('kaggle_url', models.URLField(blank=True, default='https://www.kaggle.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('resume_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
