# Generated by Django 5.2.17 on 2026-09-06 08:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bgm_file',
            field=models.FileField(blank=True, help_text='Upload custom MP3 audio (up to 100MB). To switch back to default, simply clear/delete this file.', null=True, upload_to='bgm/', validators=[core.models.validate_bgm_file], verbose_name='Custom BGM Audio File (MP3, Max 100MB)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bgm_title',
            field=models.CharField(blank=True, default='Arabic Ambient BGM', help_text='Name of the currently active background track', max_length=150, verbose_name='BGM Title / Track Name'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_bgm_enabled',
            field=models.BooleanField(default=True, help_text='Uncheck to pause / silence music portfolio-wide.', verbose_name='Enable Background Music (BGM)'),
        ),
    ]
