# Generated by Django 5.2.17 on 2026-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_bgm_file_sitesetting_bgm_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
            ],
            options={
                'verbose_name': 'Background Music (BGM)',
                'verbose_name_plural': 'Background Music (BGM)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesetting',),
        ),
    ]
