# Generated by Django 5.2.17 on 2026-09-06 08:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backgroundmusic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundMusic',
        ),
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Background Music Track', help_text='Title or description of the background music', max_length=200, verbose_name='Track Title')),
                ('audio_file', models.FileField(blank=True, help_text='Upload custom MP3 audio (up to 100MB). When uploaded, this plays as base BGM. Delete/clear file to play default arabic-bgm.mp3.', null=True, upload_to='bgm/', validators=[core.models.validate_bgm_file], verbose_name='Upload MP3 File (Max 100MB)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause/silence music portfolio-wide.', verbose_name='Play / Enable Music')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Background Music (BGM)',
                'verbose_name_plural': 'Background Music (BGM)',
                'ordering': ['-updated_at'],
            },
        ),
    ]
