# Generated by Django 6.1 on 2026-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. B.Sc. in Computer Science & Engineering / M.Sc.', max_length=200)),
                ('institution', models.CharField(help_text='e.g. University Name / College', max_length=255)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=150)),
                ('start_year', models.CharField(default='2020', max_length=50)),
                ('end_year', models.CharField(default='2024', help_text='e.g. 2024 or Present', max_length=50)),
                ('grade_or_cgpa', models.CharField(blank=True, default='', help_text='e.g. CGPA: 3.85 / 4.00', max_length=100)),
                ('field_of_study', models.CharField(blank=True, default='Computer Science & Data Science', max_length=255)),
                ('thesis_or_description', models.TextField(blank=True, default='', help_text='Key coursework, thesis topic, or research accomplishments')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Machine Learning Engineer / AI Researcher', max_length=200)),
                ('company', models.CharField(help_text='e.g. AI Research Lab / Company Name', max_length=200)),
                ('period', models.CharField(default='2024 - Present', max_length=100)),
                ('location', models.CharField(default='Remote / Dhaka', max_length=150)),
                ('job_type', models.CharField(blank=True, default='Full-Time / Research', max_length=100)),
                ('description', models.TextField(help_text='Key accomplishments and impact in this role')),
                ('technologies', models.CharField(default='PyTorch, Transformers, LangChain, Python', help_text='Comma-separated list of tools used', max_length=500)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experience / Job',
                'verbose_name_plural': 'Experiences & Jobs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Applied AI & ML', 'Applied AI & ML'), ('NLP & LLMs', 'NLP & LLMs'), ('Computer Vision', 'Computer Vision'), ('Data Engineering', 'Data Engineering')], default='Applied AI & ML', max_length=100)),
                ('image_url', models.CharField(blank=True, default='/projects/project1.png', help_text='Local path e.g. /projects/project1.png or full web URL', max_length=500)),
                ('image_file', models.ImageField(blank=True, help_text='Or upload an image', null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True, default='', help_text='Live demo or paper demo URL')),
                ('github_url', models.URLField(blank=True, default='', help_text='GitHub repository URL')),
                ('tech_stack', models.CharField(default='PyTorch, Transformers, FastAPI, Docker', help_text='Comma-separated technologies', max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publisher', models.CharField(default='arXiv / IEEE', help_text='e.g. arXiv / IEEE / Springer', max_length=200)),
                ('publication_date', models.CharField(default='2025', max_length=100)),
                ('abstract', models.TextField()),
                ('paper_url', models.URLField(blank=True, default='', help_text='Link to paper website / DOI')),
                ('pdf_url', models.URLField(blank=True, default='', help_text='Direct link to PDF download')),
                ('tags', models.CharField(default='Deep Learning, NLP, Transformers', help_text='Comma-separated tags', max_length=400)),
                ('citations_count', models.PositiveIntegerField(blank=True, default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Research Paper',
                'verbose_name_plural': 'Research & Papers',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
